dist: trusty
sudo: false
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - libcurl3
language: ruby
cache: bundler
rvm:
  - 2.2
script: 
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --allow-hash-href true --check-html true --check-external-hash true
  - curl --silent --show-error https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.michael-shogren.com | grep -q '\[Valid Atom'
