name: Michael Shogren's Blog
url: https://www.michael-shogren.com
author: Michael Shogren
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate: 2
paginate_path: "/page:num/"
sass:
  style: compressed
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
