name: Michael Shogren's Blog
title: Michael Shogren's Blog
url: https://michael-shogren.com
repository: "mshogren/mshogren.github.io"
url: https://michael-shogren.com
author: Michael Shogren
markdown: GFM
highlighter: rouge
excerpt_separator: <!--more-->
paginate: 4
paginate_path: "/page:num/"
staticman_url: https://mshogren-staticman.herokuapp.com/v2/entry/mshogren/mshogren.github.io/master/comments
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
